services:

  postgres:
    image: postgres:16
    container_name: quickroom-db
    restart: always

    env_file:
      - .env

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend

    container_name: quickroom-backend

    depends_on:
      - postgres

    env_file:
      - .env

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}

    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend

    container_name: quickroom-frontend

    depends_on:
      - backend

    ports:
      - "3000:80"

volumes:
  postgres-data: